export const countryMeta: Record<string, { id: string; cuisine: string; flag: string }> = {
  "Afghanistan": { id: "AF", cuisine: "World", flag: "" },
  "Albania": { id: "AL", cuisine: "World", flag: "" },
  "Algeria": { id: "DZ", cuisine: "World", flag: "" },
  "American Samoa": { id: "AS", cuisine: "World", flag: "" },
  "Andorra": { id: "AD", cuisine: "World", flag: "" },
  "Angola": { id: "AO", cuisine: "World", flag: "" },
  "Anguilla": { id: "AI", cuisine: "World", flag: "" },
  "Antarctica": { id: "AQ", cuisine: "World", flag: "" },
  "Antigua and Barbuda": { id: "AG", cuisine: "World", flag: "" },
  "Argentina": { id: "AR", cuisine: "World", flag: "" },
  "Armenia": { id: "AM", cuisine: "World", flag: "" },
  "Aruba": { id: "AW", cuisine: "World", flag: "" },
  "Australia": { id: "AU", cuisine: "World", flag: "" },
  "Austria": { id: "AT", cuisine: "World", flag: "" },
  "Azerbaijan": { id: "AZ", cuisine: "World", flag: "" },
  "Bahamas": { id: "BS", cuisine: "World", flag: "" },
  "Bahrain": { id: "BH", cuisine: "World", flag: "" },
  "Bangladesh": { id: "BD", cuisine: "World", flag: "" },
  "Barbados": { id: "BB", cuisine: "World", flag: "" },
  "Belarus": { id: "BY", cuisine: "World", flag: "" },
  "Belgium": { id: "BE", cuisine: "World", flag: "" },
  "Belize": { id: "BZ", cuisine: "World", flag: "" },
  "Benin": { id: "BJ", cuisine: "World", flag: "" },
  "Bermuda": { id: "BM", cuisine: "World", flag: "" },
  "Bhutan": { id: "BT", cuisine: "World", flag: "" },
  "Bolivia, Plurinational State of": { id: "BO", cuisine: "World", flag: "" },
  "Bonaire, Sint Eustatius and Saba": { id: "BQ", cuisine: "World", flag: "" },
  "Bosnia and Herzegovina": { id: "BA", cuisine: "World", flag: "" },
  "Botswana": { id: "BW", cuisine: "World", flag: "" },
  "Bouvet Island": { id: "BV", cuisine: "World", flag: "" },
  "Brazil": { id: "BR", cuisine: "World", flag: "" },
  "British Indian Ocean Territory": { id: "IO", cuisine: "World", flag: "" },
  "Brunei Darussalam": { id: "BN", cuisine: "World", flag: "" },
  "Bulgaria": { id: "BG", cuisine: "World", flag: "" },
  "Burkina Faso": { id: "BF", cuisine: "World", flag: "" },
  "Burundi": { id: "BI", cuisine: "World", flag: "" },
  "Cabo Verde": { id: "CV", cuisine: "World", flag: "" },
  "Cambodia": { id: "KH", cuisine: "World", flag: "" },
  "Cameroon": { id: "CM", cuisine: "World", flag: "" },
  "Canada": { id: "CA", cuisine: "World", flag: "" },
  "Cayman Islands": { id: "KY", cuisine: "World", flag: "" },
  "Central African Republic": { id: "CF", cuisine: "World", flag: "" },
  "Chad": { id: "TD", cuisine: "World", flag: "" },
  "Chile": { id: "CL", cuisine: "World", flag: "" },
  "China": { id: "CN", cuisine: "World", flag: "" },
  "Christmas Island": { id: "CX", cuisine: "World", flag: "" },
  "Cocos (Keeling) Islands": { id: "CC", cuisine: "World", flag: "" },
  "Colombia": { id: "CO", cuisine: "World", flag: "" },
  "Comoros": { id: "KM", cuisine: "World", flag: "" },
  "Congo": { id: "CG", cuisine: "World", flag: "" },
  "Congo, The Democratic Republic of the": { id: "CD", cuisine: "World", flag: "" },
  "Cook Islands": { id: "CK", cuisine: "World", flag: "" },
  "Costa Rica": { id: "CR", cuisine: "World", flag: "" },
  "Croatia": { id: "HR", cuisine: "World", flag: "" },
  "Cuba": { id: "CU", cuisine: "World", flag: "" },
  "Curaçao": { id: "CW", cuisine: "World", flag: "" },
  "Cyprus": { id: "CY", cuisine: "World", flag: "" },
  "Czechia": { id: "CZ", cuisine: "World", flag: "" },
  "Côte d'Ivoire": { id: "CI", cuisine: "World", flag: "" },
  "Denmark": { id: "DK", cuisine: "World", flag: "" },
  "Djibouti": { id: "DJ", cuisine: "World", flag: "" },
  "Dominica": { id: "DM", cuisine: "World", flag: "" },
  "Dominican Republic": { id: "DO", cuisine: "World", flag: "" },
  "Ecuador": { id: "EC", cuisine: "World", flag: "" },
  "Egypt": { id: "EG", cuisine: "World", flag: "" },
  "El Salvador": { id: "SV", cuisine: "World", flag: "" },
  "Equatorial Guinea": { id: "GQ", cuisine: "World", flag: "" },
  "Eritrea": { id: "ER", cuisine: "World", flag: "" },
  "Estonia": { id: "EE", cuisine: "World", flag: "" },
  "Eswatini": { id: "SZ", cuisine: "World", flag: "" },
  "Ethiopia": { id: "ET", cuisine: "World", flag: "" },
  "Falkland Islands (Malvinas)": { id: "FK", cuisine: "World", flag: "" },
  "Faroe Islands": { id: "FO", cuisine: "World", flag: "" },
  "Fiji": { id: "FJ", cuisine: "World", flag: "" },
  "Finland": { id: "FI", cuisine: "World", flag: "" },
  "France": { id: "FR", cuisine: "World", flag: "" },
  "French Guiana": { id: "GF", cuisine: "World", flag: "" },
  "French Polynesia": { id: "PF", cuisine: "World", flag: "" },
  "French Southern Territories": { id: "TF", cuisine: "World", flag: "" },
  "Gabon": { id: "GA", cuisine: "World", flag: "" },
  "Gambia": { id: "GM", cuisine: "World", flag: "" },
  "Georgia": { id: "GE", cuisine: "World", flag: "" },
  "Germany": { id: "DE", cuisine: "World", flag: "" },
  "Ghana": { id: "GH", cuisine: "World", flag: "" },
  "Gibraltar": { id: "GI", cuisine: "World", flag: "" },
  "Greece": { id: "GR", cuisine: "World", flag: "" },
  "Greenland": { id: "GL", cuisine: "World", flag: "" },
  "Grenada": { id: "GD", cuisine: "World", flag: "" },
  "Guadeloupe": { id: "GP", cuisine: "World", flag: "" },
  "Guam": { id: "GU", cuisine: "World", flag: "" },
  "Guatemala": { id: "GT", cuisine: "World", flag: "" },
  "Guernsey": { id: "GG", cuisine: "World", flag: "" },
  "Guinea": { id: "GN", cuisine: "World", flag: "" },
  "Guinea-Bissau": { id: "GW", cuisine: "World", flag: "" },
  "Guyana": { id: "GY", cuisine: "World", flag: "" },
  "Haiti": { id: "HT", cuisine: "World", flag: "" },
  "Heard Island and McDonald Islands": { id: "HM", cuisine: "World", flag: "" },
  "Holy See (Vatican City State)": { id: "VA", cuisine: "World", flag: "" },
  "Honduras": { id: "HN", cuisine: "World", flag: "" },
  "Hong Kong": { id: "HK", cuisine: "World", flag: "" },
  "Hungary": { id: "HU", cuisine: "World", flag: "" },
  "Iceland": { id: "IS", cuisine: "World", flag: "" },
  "India": { id: "IN", cuisine: "World", flag: "" },
  "Indonesia": { id: "ID", cuisine: "World", flag: "" },
  "Iran, Islamic Republic of": { id: "IR", cuisine: "World", flag: "" },
  "Iraq": { id: "IQ", cuisine: "World", flag: "" },
  "Ireland": { id: "IE", cuisine: "World", flag: "" },
  "Isle of Man": { id: "IM", cuisine: "World", flag: "" },
  "Israel": { id: "IL", cuisine: "World", flag: "" },
  "Italy": { id: "IT", cuisine: "World", flag: "" },
  "Jamaica": { id: "JM", cuisine: "World", flag: "" },
  "Japan": { id: "JP", cuisine: "World", flag: "" },
  "Jersey": { id: "JE", cuisine: "World", flag: "" },
  "Jordan": { id: "JO", cuisine: "World", flag: "" },
  "Kazakhstan": { id: "KZ", cuisine: "World", flag: "" },
  "Kenya": { id: "KE", cuisine: "World", flag: "" },
  "Kiribati": { id: "KI", cuisine: "World", flag: "" },
  "Korea, Democratic People's Republic of": { id: "KP", cuisine: "World", flag: "" },
  "Korea, Republic of": { id: "KR", cuisine: "World", flag: "" },
  "Kuwait": { id: "KW", cuisine: "World", flag: "" },
  "Kyrgyzstan": { id: "KG", cuisine: "World", flag: "" },
  "Lao People's Democratic Republic": { id: "LA", cuisine: "World", flag: "" },
  "Latvia": { id: "LV", cuisine: "World", flag: "" },
  "Lebanon": { id: "LB", cuisine: "World", flag: "" },
  "Lesotho": { id: "LS", cuisine: "World", flag: "" },
  "Liberia": { id: "LR", cuisine: "World", flag: "" },
  "Libya": { id: "LY", cuisine: "World", flag: "" },
  "Liechtenstein": { id: "LI", cuisine: "World", flag: "" },
  "Lithuania": { id: "LT", cuisine: "World", flag: "" },
  "Luxembourg": { id: "LU", cuisine: "World", flag: "" },
  "Macao": { id: "MO", cuisine: "World", flag: "" },
  "Madagascar": { id: "MG", cuisine: "World", flag: "" },
  "Malawi": { id: "MW", cuisine: "World", flag: "" },
  "Malaysia": { id: "MY", cuisine: "World", flag: "" },
  "Maldives": { id: "MV", cuisine: "World", flag: "" },
  "Mali": { id: "ML", cuisine: "World", flag: "" },
  "Malta": { id: "MT", cuisine: "World", flag: "" },
  "Marshall Islands": { id: "MH", cuisine: "World", flag: "" },
  "Martinique": { id: "MQ", cuisine: "World", flag: "" },
  "Mauritania": { id: "MR", cuisine: "World", flag: "" },
  "Mauritius": { id: "MU", cuisine: "World", flag: "" },
  "Mayotte": { id: "YT", cuisine: "World", flag: "" },
  "Mexico": { id: "MX", cuisine: "World", flag: "" },
  "Micronesia, Federated States of": { id: "FM", cuisine: "World", flag: "" },
  "Moldova, Republic of": { id: "MD", cuisine: "World", flag: "" },
  "Monaco": { id: "MC", cuisine: "World", flag: "" },
  "Mongolia": { id: "MN", cuisine: "World", flag: "" },
  "Montenegro": { id: "ME", cuisine: "World", flag: "" },
  "Montserrat": { id: "MS", cuisine: "World", flag: "" },
  "Morocco": { id: "MA", cuisine: "World", flag: "" },
  "Mozambique": { id: "MZ", cuisine: "World", flag: "" },
  "Myanmar": { id: "MM", cuisine: "World", flag: "" },
  "Namibia": { id: "NA", cuisine: "World", flag: "" },
  "Nauru": { id: "NR", cuisine: "World", flag: "" },
  "Nepal": { id: "NP", cuisine: "World", flag: "" },
  "Netherlands": { id: "NL", cuisine: "World", flag: "" },
  "New Caledonia": { id: "NC", cuisine: "World", flag: "" },
  "New Zealand": { id: "NZ", cuisine: "World", flag: "" },
  "Nicaragua": { id: "NI", cuisine: "World", flag: "" },
  "Niger": { id: "NE", cuisine: "World", flag: "" },
  "Nigeria": { id: "NG", cuisine: "World", flag: "" },
  "Niue": { id: "NU", cuisine: "World", flag: "" },
  "Norfolk Island": { id: "NF", cuisine: "World", flag: "" },
  "North Macedonia": { id: "MK", cuisine: "World", flag: "" },
  "Northern Mariana Islands": { id: "MP", cuisine: "World", flag: "" },
  "Norway": { id: "NO", cuisine: "World", flag: "" },
  "Oman": { id: "OM", cuisine: "World", flag: "" },
  "Pakistan": { id: "PK", cuisine: "World", flag: "" },
  "Palau": { id: "PW", cuisine: "World", flag: "" },
  "Palestine, State of": { id: "PS", cuisine: "World", flag: "" },
  "Panama": { id: "PA", cuisine: "World", flag: "" },
  "Papua New Guinea": { id: "PG", cuisine: "World", flag: "" },
  "Paraguay": { id: "PY", cuisine: "World", flag: "" },
  "Peru": { id: "PE", cuisine: "World", flag: "" },
  "Philippines": { id: "PH", cuisine: "World", flag: "" },
  "Pitcairn": { id: "PN", cuisine: "World", flag: "" },
  "Poland": { id: "PL", cuisine: "World", flag: "" },
  "Portugal": { id: "PT", cuisine: "World", flag: "" },
  "Puerto Rico": { id: "PR", cuisine: "World", flag: "" },
  "Qatar": { id: "QA", cuisine: "World", flag: "" },
  "Romania": { id: "RO", cuisine: "World", flag: "" },
  "Russian Federation": { id: "RU", cuisine: "World", flag: "" },
  "Rwanda": { id: "RW", cuisine: "World", flag: "" },
  "Réunion": { id: "RE", cuisine: "World", flag: "" },
  "Saint Barthélemy": { id: "BL", cuisine: "World", flag: "" },
  "Saint Helena, Ascension and Tristan da Cunha": { id: "SH", cuisine: "World", flag: "" },
  "Saint Kitts and Nevis": { id: "KN", cuisine: "World", flag: "" },
  "Saint Lucia": { id: "LC", cuisine: "World", flag: "" },
  "Saint Martin (French part)": { id: "MF", cuisine: "World", flag: "" },
  "Saint Pierre and Miquelon": { id: "PM", cuisine: "World", flag: "" },
  "Saint Vincent and the Grenadines": { id: "VC", cuisine: "World", flag: "" },
  "Samoa": { id: "WS", cuisine: "World", flag: "" },
  "San Marino": { id: "SM", cuisine: "World", flag: "" },
  "Sao Tome and Principe": { id: "ST", cuisine: "World", flag: "" },
  "Saudi Arabia": { id: "SA", cuisine: "World", flag: "" },
  "Senegal": { id: "SN", cuisine: "World", flag: "" },
  "Serbia": { id: "RS", cuisine: "World", flag: "" },
  "Seychelles": { id: "SC", cuisine: "World", flag: "" },
  "Sierra Leone": { id: "SL", cuisine: "World", flag: "" },
  "Singapore": { id: "SG", cuisine: "World", flag: "" },
  "Sint Maarten (Dutch part)": { id: "SX", cuisine: "World", flag: "" },
  "Slovakia": { id: "SK", cuisine: "World", flag: "" },
  "Slovenia": { id: "SI", cuisine: "World", flag: "" },
  "Solomon Islands": { id: "SB", cuisine: "World", flag: "" },
  "Somalia": { id: "SO", cuisine: "World", flag: "" },
  "South Africa": { id: "ZA", cuisine: "World", flag: "" },
  "South Georgia and the South Sandwich Islands": { id: "GS", cuisine: "World", flag: "" },
  "South Sudan": { id: "SS", cuisine: "World", flag: "" },
  "Spain": { id: "ES", cuisine: "World", flag: "" },
  "Sri Lanka": { id: "LK", cuisine: "World", flag: "" },
  "Sudan": { id: "SD", cuisine: "World", flag: "" },
  "Suriname": { id: "SR", cuisine: "World", flag: "" },
  "Svalbard and Jan Mayen": { id: "SJ", cuisine: "World", flag: "" },
  "Sweden": { id: "SE", cuisine: "World", flag: "" },
  "Switzerland": { id: "CH", cuisine: "World", flag: "" },
  "Syrian Arab Republic": { id: "SY", cuisine: "World", flag: "" },
  "Taiwan, Province of China": { id: "TW", cuisine: "World", flag: "" },
  "Tajikistan": { id: "TJ", cuisine: "World", flag: "" },
  "Tanzania, United Republic of": { id: "TZ", cuisine: "World", flag: "" },
  "Thailand": { id: "TH", cuisine: "World", flag: "" },
  "Timor-Leste": { id: "TL", cuisine: "World", flag: "" },
  "Togo": { id: "TG", cuisine: "World", flag: "" },
  "Tokelau": { id: "TK", cuisine: "World", flag: "" },
  "Tonga": { id: "TO", cuisine: "World", flag: "" },
  "Trinidad and Tobago": { id: "TT", cuisine: "World", flag: "" },
  "Tunisia": { id: "TN", cuisine: "World", flag: "" },
  "Turkey": { id: "TR", cuisine: "World", flag: "" },
  "Turkmenistan": { id: "TM", cuisine: "World", flag: "" },
  "Turks and Caicos Islands": { id: "TC", cuisine: "World", flag: "" },
  "Tuvalu": { id: "TV", cuisine: "World", flag: "" },
  "Uganda": { id: "UG", cuisine: "World", flag: "" },
  "Ukraine": { id: "UA", cuisine: "World", flag: "" },
  "United Arab Emirates": { id: "AE", cuisine: "World", flag: "" },
  "United Kingdom": { id: "GB", cuisine: "World", flag: "" },
  "United States": { id: "US", cuisine: "World", flag: "" },
  "United States Minor Outlying Islands": { id: "UM", cuisine: "World", flag: "" },
  "Uruguay": { id: "UY", cuisine: "World", flag: "" },
  "Uzbekistan": { id: "UZ", cuisine: "World", flag: "" },
  "Vanuatu": { id: "VU", cuisine: "World", flag: "" },
  "Venezuela, Bolivarian Republic of": { id: "VE", cuisine: "World", flag: "" },
  "Viet Nam": { id: "VN", cuisine: "World", flag: "" },
  "Virgin Islands, British": { id: "VG", cuisine: "World", flag: "" },
  "Virgin Islands, U.S.": { id: "VI", cuisine: "World", flag: "" },
  "Wallis and Futuna": { id: "WF", cuisine: "World", flag: "" },
  "Western Sahara": { id: "EH", cuisine: "World", flag: "" },
  "Yemen": { id: "YE", cuisine: "World", flag: "" },
  "Zambia": { id: "ZM", cuisine: "World", flag: "" },
  "Zimbabwe": { id: "ZW", cuisine: "World", flag: "" },
  "Åland Islands": { id: "AX", cuisine: "World", flag: "" },
}